name: bump_deps

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  bump_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with: { version: 10 }
      - run: |
          pnpm update
          pnpm install --lockfile-only

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '[bot] Bump deps'
